title: Launching Jupyter on TACC
description: How to run Jupyter Notebook on TACC compute nodes from the terminal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - README.md